/**
 * 导出工具函数
 * 支持导出为图片、PDF、Markdown，并支持预览
 */

// --- 核心辅助函数：构建 DOM ---

/**
 * HTML转义
 */
function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * 准备导出容器的 DOM 结构 (macOS 风格)
 * @param {Array} messages - 消息列表
 * @param {string} title - 标题
 * @param {boolean} isDark - 主题
 * @param {Set} messageIndices - 选中的消息索引
 * @returns {HTMLElement} 构建好的 DOM 元素
 */
export function prepareMacOSContainerDOM(messages, title = '对话导出', isDark = false, messageIndices = null) {
  const container = document.createElement('div');
  // 默认样式，适合直接展示
  container.className = 'export-container-preview';
  container.style.width = '100%';
  container.style.maxWidth = '900px';
  container.style.margin = '0 auto';

  // macOS窗口样式（与 SummaryModal.vue 统一）
  const containerBg = isDark ? '#1e1e20' : '#ffffff';
  const headerBg = isDark ? '#2a2a2c' : '#f5f5f7';
  const headerBorder = isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)';
  const textColor = isDark ? '#aaaaaa' : '#666666';

  container.innerHTML = `
    <div style="
      background: ${containerBg};
      border-radius: 16px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.2);
      overflow: hidden;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif;
      border: 1px solid ${headerBorder};
    ">
      <!-- macOS 窗口头部 -->
      <div style="
        background: ${headerBg};
        padding: 0 16px;
        height: 44px;
        display: flex;
        align-items: center;
        border-bottom: 1px solid ${headerBorder};
        position: relative;
      ">
        <!-- 红黄绿三个圆点 -->
        <div style="display: flex; gap: 8px; align-items: center; z-index: 10;">
          <div style="width: 12px; height: 12px; border-radius: 50%; background: #ff5f56; border: 0.5px solid rgba(0,0,0,0.1);"></div>
          <div style="width: 12px; height: 12px; border-radius: 50%; background: #ffbd2e; border: 0.5px solid rgba(0,0,0,0.1);"></div>
          <div style="width: 12px; height: 12px; border-radius: 50%; background: #27c93f; border: 0.5px solid rgba(0,0,0,0.1);"></div>
        </div>

        <!-- 标题（绝对居中） -->
        <div style="
            font-size: 13px;
            font-weight: 600;
            color: ${textColor};
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            white-space: nowrap;
        ">
            ${escapeHtml(title)}
        </div>
      </div>

      <!-- 消息内容容器 -->
      <div id="messages-container" style="padding: 24px; background: ${containerBg};"></div>

      <!-- 底部信息 -->
      <div style="
        padding: 12px 24px;
        background: ${isDark ? '#252527' : '#fafafa'};
        border-top: 1px solid ${isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.03)'};
        font-size: 11px;
        color: ${isDark ? '#666' : '#bbb'};
        text-align: center;
        display: flex;
        justify-content: space-between;
      ">
        <span>Generated by Antigravity AI</span>
        <span>${new Date().toLocaleDateString()}</span>
      </div>
    </div>
  `;

  // 获取消息容器
  const messagesContainer = container.querySelector('#messages-container');

  // 获取页面上真实的消息元素
  const messageElements = Array.from(document.querySelectorAll('.py-3.w-full.flex.justify-center'))
    .filter(el => {
      return el.querySelector('.flex.flex-col.gap-2.min-w-0.flex-1.relative');
    });

  const indicesToExport = messageIndices || new Set(Array.from({ length: messages.length }, (_, i) => i));

  let exportedCount = 0;

  messageElements.forEach((msgElement, index) => {
    if (indicesToExport.has(index) && exportedCount < messages.length) {
      const clonedMsg = msgElement.cloneNode(true);

      // DOM Cleanup & Styling Fixes

      // 1. Remove Checkboxes
      const checkbox = clonedMsg.querySelector('input[type="checkbox"]');
      if (checkbox && checkbox.parentElement) {
        checkbox.parentElement.remove();
      }

      // 2. Fix Model Tag Style
      // 恢复漂亮的视觉样式，但使用对 html2canvas 友好的显式 CSS
      const modelTag = clonedMsg.querySelector('span[class*="bg-blue-100"], span[class*="bg-chatgpt-"]');
      if (modelTag) {
          // 清除可能导致偏移的 Tailwind 类和样式
          modelTag.className = '';
          modelTag.removeAttribute('style');

          Object.assign(modelTag.style, {
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
              height: '18px',
              padding: '0 6px',
              marginLeft: '6px',
              backgroundColor: isDark ? 'rgba(59, 130, 246, 0.2)' : 'rgba(219, 234, 254, 1)', // blue-100 / dark
              color: isDark ? '#60a5fa' : '#1e40af', // blue-800 / blue-400
              borderRadius: '4px',
              fontSize: '10px',
              fontWeight: '500',
              fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
              lineHeight: '1',
              verticalAlign: 'middle',
              transform: 'none', // 禁止变换，防止偏移
              border: isDark ? '1px solid rgba(59, 130, 246, 0.3)' : 'none'
          });

          // 确保父容器对齐
          if (modelTag.parentElement) {
              modelTag.parentElement.style.display = 'flex';
              modelTag.parentElement.style.alignItems = 'center';
              modelTag.parentElement.style.flexWrap = 'wrap';
          }
      }

      // 3. Remove Action Buttons (except Code Copy)
      const actionButtons = clonedMsg.querySelectorAll('button');
      actionButtons.forEach(btn => {
        if (!btn.closest('.code-block-header')) {
          btn.remove();
        }
      });

      // 4. Force Width
      clonedMsg.style.width = '100%';
      clonedMsg.style.maxWidth = '100%';

      messagesContainer.appendChild(clonedMsg);
      exportedCount++;
    }
  });

  return container;
}

/**
 * 生成 Markdown 内容
 */
export function generateMarkdownContent(messages, title = '对话导出', messageIndices = null) {
  let markdown = `# ${title}\n\n`;
  markdown += `> 导出时间: ${new Date().toLocaleString('zh-CN')}\n\n`;
  markdown += `---\n\n`;

  const indicesToExport = messageIndices || new Set(Array.from({ length: messages.length }, (_, i) => i));

  messages.forEach((msg, index) => {
    if (!indicesToExport.has(index)) return;

    const role = msg.role === 'user' ? '👤 用户' : '🤖 AI';
    const modelInfo = (msg.role !== 'user' && msg.modelId) ? ` (${msg.modelId})` : '';
    const time = msg.timestamp ? ` - ${new Date(msg.timestamp).toLocaleTimeString()}` : '';

    markdown += `## ${role}${modelInfo}${time}\n\n`;
    markdown += `${msg.content || ''}\n\n`;

    if (msg.images && msg.images.length > 0) {
      msg.images.forEach((img, idx) => {
        markdown += `![图片${idx + 1}](${img})\n\n`;
      });
    }

    markdown += `---\n\n`;
  });

  return markdown;
}


// --- 核心执行函数：下载 ---

/**
 * 通用渲染函数：将 DOM 渲染为 Canvas
 * 使用 Clone + 离屏渲染技术，避免滚动条和视口限制
 */
async function renderElementToCanvas(element) {
    const html2canvas = (await import('html2canvas')).default;

    // 1. Clone 元素，避免影响现有视图
    const clone = element.cloneNode(true);

    // 2. 设置固定样式，确保完整渲染
    Object.assign(clone.style, {
        position: 'fixed',
        left: '-10000px',
        top: '0',
        width: '800px', // 固定宽度，类似 A4 比例或标准网页宽
        height: 'auto',
        zIndex: '-1000',
        overflow: 'visible' // 确保内容不被裁剪
    });

    document.body.appendChild(clone);

    // 等待一小段时间确保样式应用和某些资源加载
    await new Promise(resolve => setTimeout(resolve, 100));

    try {
        const canvas = await html2canvas(clone, {
            backgroundColor: null,
            scale: 2, // 高清
            logging: false,
            useCORS: true,
            allowTaint: true,
            foreignObjectRendering: false,
            windowWidth: clone.scrollWidth,
            windowHeight: clone.scrollHeight
        });
        return canvas;
    } finally {
        // 清理 Clone
        if (clone && clone.parentNode) {
            clone.parentNode.removeChild(clone);
        }
    }
}

/**
 * 下载 DOM 为图片
 */
export async function downloadDOMAsImage(element, filename) {
  try {
    const canvas = await renderElementToCanvas(element);

    const link = document.createElement('a');
    link.download = filename.endsWith('.png') ? filename : `${filename}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();

    return { success: true };
  } catch (error) {
    console.error('导出图片失败:', error);
    return { success: false, error: error.message };
  }
}

/**
 * 下载 DOM 为 PDF
 */
export async function downloadDOMAsPDF(element, filename) {
  try {
    const { jsPDF } = await import('jspdf');

    // 使用通用渲染函数
    const canvas = await renderElementToCanvas(element);

    const imgData = canvas.toDataURL('image/png');
    // A4 尺寸 (mm)
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = 210;
    const pdfHeight = 297;

    // 计算图片在 PDF 中的尺寸（保持比例适配宽度）
    const imgProps = pdf.getImageProperties(imgData);
    const imgHeight = (imgProps.height * pdfWidth) / imgProps.width;

    let heightLeft = imgHeight;
    let position = 0;

    // 第一页
    pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
    heightLeft -= pdfHeight;

    // 后续页
    while (heightLeft > 0) {
      position = heightLeft - imgHeight; // 这里的计算是: 当前剩余顶部位置
      // 实际上 jspdf 分页添加图片的逻辑是: 调整 y 坐标为负值，让图片上移
      // position 应该是 -297, -594 ...
      // 修正算法：
      // Page 2: position should be -297

      pdf.addPage();
      // 计算新的偏移量
      // 上一次的 position 是 0（相对于第一页顶端）
      // 下一页我们要显示的是原本 297mm 处的内容，让它出现在新页面的 0mm 处
      // 所以 y = -297
      // 我们可以维护一个累加的 offset

      // 重置 position 逻辑，直接用 page index
      const pageIndex = pdf.internal.getNumberOfPages() - 1; // 0-based, now 1
      position = -pageIndex * pdfHeight;

      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
      heightLeft -= pdfHeight;
    }

    pdf.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
    return { success: true };
  } catch (error) {
    console.error('导出PDF失败:', error);
    return { success: false, error: error.message };
  }
}

/**
 * 下载 Markdown 字符串
 */
export function downloadMarkdownString(content, filename) {
    try {
        const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
        const link = document.createElement('a');
        link.download = filename.endsWith('.md') ? filename : `${filename}.md`;
        link.href = URL.createObjectURL(blob);
        link.click();
        URL.revokeObjectURL(link.href);
        return { success: true };
    } catch (error) {
        console.error('导出Markdown失败:', error);
        return { success: false, error: error.message };
    }
}


// --- 兼容旧 API (Direct Export) ---

export async function exportAsImage(messages, title, isDark, messageIndices) {
    const element = prepareMacOSContainerDOM(messages, title, isDark, messageIndices);
    // 放入 body 隐藏
    element.style.position = 'fixed';
    element.style.left = '-9999px';
    element.style.top = '0';
    document.body.appendChild(element);
    try {
        return await downloadDOMAsImage(element, `chat-export-${Date.now()}`);
    } finally {
        element.remove();
    }
}

export async function exportAsPDF(messages, title, isDark, messageIndices) {
    const element = prepareMacOSContainerDOM(messages, title, isDark, messageIndices);
    element.style.position = 'fixed';
    element.style.left = '-9999px';
    element.style.top = '0';
    document.body.appendChild(element);
    try {
        await new Promise(r => setTimeout(r, 100)); // wait for style
        return await downloadDOMAsPDF(element, `chat-export-${Date.now()}`);
    } finally {
        element.remove();
    }
}

export function exportAsMarkdown(messages, title, messageIndices) {
    const content = generateMarkdownContent(messages, title, messageIndices);
    return downloadMarkdownString(content, `chat-export-${Date.now()}`);
}
